# Generated by Django 5.0.1 on 2024-01-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(choices=[('IMKT', 'ИМКТ'), ('IMO', 'ИМО'), ('PI', 'ПИ'), ('SHIGN', 'ШИГН'), ('SHP', 'ШП'), ('SHM', 'ШМ'), ('SHEM', 'ШЭМ'), ('VISHRIMI', 'ВИШРИМИ')], max_length=10),
        ),
    ]
