# Generated by Django 5.0.1 on 2024-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(choices=[('IMKT', 'ИМКТ'), ('IMO', 'ИМО'), ('PI', 'ПИ'), ('SHIGN', 'ШИГН'), ('SHP', 'ШП'), ('SHM', 'ШМ'), ('SHEM', 'ШЭМ'), ('VISHRIMI', 'ВИШРИМИ')], max_length=10, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(verbose_name='Инетересы или обо мне'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в телеграмм'),
        ),
    ]
